//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boking
    {
        public Boking()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string OrderNbr { get; set; }
        public decimal OrderAmount { get; set; }
        public System.DateTime BookingDay { get; set; }
        public short PartOfTheDay { get; set; }
        public string DeliveryCost { get; set; }
        public string WayOfDelivery { get; set; }
        public int NbrItems { get; set; }
        public string Type { get; set; }
        public decimal Distance { get; set; }
        public string Zone { get; set; }
        public bool Pickup { get; set; }
        public int NbrItemsPickup { get; set; }
        public bool PayBySupplier { get; set; }
        public string Remarks { get; set; }
        public bool Sms { get; set; }
        public bool Payed { get; set; }
        public bool Email { get; set; }
        public bool Done { get; set; }
        public string Status { get; set; }
        public bool Canceled { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User CreatedBy { get; set; }
        public virtual User Car { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
