//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QTransportModelContainer : DbContext
    {
        public QTransportModelContainer()
            : base("name=QTransportModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Car> CarSet { get; set; }
        public DbSet<Customer> CustomerSet { get; set; }
        public DbSet<Boking> BokingSet { get; set; }
        public DbSet<Product> ProductSet { get; set; }
    }
}
